# Одновременные ошибки через ```errgroup```

Используй ```errgroup.Group``` для обработки 10 заданий.

Пусть функция возвращает ошибку при ```data == 5```.

Обработай ```err```, возвращённую ```g.Wait()```.